

- hosts: all
  vars_files:
    - host_vars/serverevn.yaml
  gather_facts: yes
  pre_tasks:
    - name: 'Install Python2'
      raw: sudo apt-get update; sudo apt-get -y install python

  roles:
    - role: common
    - role: docker